name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 2.12.3
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  nginx-123:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '1.23.4'
        tags: 1.23,1,latest
        platform: linux/amd64,linux/arm64
  nginx-122:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '1.22.1'
        tags: '1.22'
        platform: linux/amd64,linux/arm64
  nginx-121:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '1.21.6'
        tags: '1.21'
        platform: linux/amd64,linux/arm64
  nginx-120:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '1.20.2'
        tags: '1.20'
        platform: linux/amd64,linux/arm64
  nginx-119:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '1.19.10'
        tags: 1.19
        platform: linux/amd64,linux/arm64
